version: "3.8"
services:
  backend:
    build:
      context: ./packages/backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
      - ./shared:/shared
    depends_on:
      - db

  frontend:
    build:
      context: ./packages/frontend
    ports:
      - "5173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
      - ./shared:/shared

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bienal_user
      POSTGRES_PASSWORD: bienal_password
      POSTGRES_DB: bienal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
